<?php

// This is a compiled Agavi configuration file
// Compiled from: /data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/app/modules/Default/config/autoload.xml
// Generated by: AgaviAutoloadConfigHandler
// Date: 2011-11-28T16:38:18+0000

return array (
  'ClassicDefaultBaseAction' => '/data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/app/modules/Default/lib/action/ClassicDefaultBaseAction.class.php',
  'ClassicDefaultBaseModel' => '/data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/app/modules/Default/lib/model/ClassicDefaultBaseModel.class.php',
  'ClassicDefaultBaseView' => '/data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/app/modules/Default/lib/view/ClassicDefaultBaseView.class.php',
);

?>