<?php

// This is a compiled Agavi configuration file
// Compiled from: /data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/app/config/compile.xml
// Generated by: AgaviCompileConfigHandler
// Date: 2011-11-28T16:38:18+0000

require('/data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/libs/agavi/src/util/AgaviAttributeHolder.class.php');
require('/data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/libs/agavi/src/action/AgaviAction.class.php');
require('/data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/libs/agavi/src/core/AgaviContext.class.php');
require('/data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/libs/agavi/src/controller/AgaviController.class.php');
require('/data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/libs/agavi/src/controller/AgaviExecutionContainer.class.php');
require('/data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/libs/agavi/src/controller/AgaviOutputType.class.php');
require('/data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/libs/agavi/src/filter/AgaviFilter.class.php');
require('/data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/libs/agavi/src/filter/AgaviDispatchFilter.class.php');
require('/data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/libs/agavi/src/filter/AgaviExecutionFilter.class.php');
require('/data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/libs/agavi/src/filter/AgaviFilterChain.class.php');
require('/data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/libs/agavi/src/renderer/AgaviRenderer.class.php');
require('/data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/libs/agavi/src/request/AgaviRequestDataHolder.class.php');
require('/data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/libs/agavi/src/request/AgaviRequest.class.php');
require('/data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/libs/agavi/src/response/AgaviResponse.class.php');
require('/data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/libs/agavi/src/routing/AgaviRouting.class.php');
require('/data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/libs/agavi/src/storage/AgaviStorage.class.php');
require('/data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/libs/agavi/src/user/AgaviUser.class.php');
require('/data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/libs/agavi/src/view/AgaviTemplateLayer.class.php');
require('/data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/libs/agavi/src/view/AgaviView.class.php');

?>