<?php

// This is a compiled Agavi configuration file
// Compiled from: /data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/app/modules/Default/config/config_handlers.xml
// Generated by: AgaviConfigHandlersConfigHandler
// Date: 2011-11-28T16:38:18+0000

return array (
)

?>