<?php

// This is a compiled Agavi configuration file
// Compiled from: /data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/app/modules/Default/config/module.xml
// Generated by: AgaviModuleConfigHandler
// Date: 2011-11-28T16:38:18+0000

$lcModuleName = strtolower($moduleName);
AgaviConfig::set(AgaviToolkit::expandVariables('modules.${moduleName}.enabled', array('moduleName' => $lcModuleName)), true, true, true);
$moduleConfig = array (
  'modules.${moduleName}.title' => 'Default Module',
  'modules.${moduleName}.version' => '1.0',
);
$moduleConfigKeys = array_keys($moduleConfig);
foreach($moduleConfigKeys as &$value) $value = AgaviToolkit::expandVariables($value, array('moduleName' => $lcModuleName));
$moduleConfig = array_combine($moduleConfigKeys, $moduleConfig);
AgaviConfig::fromArray($moduleConfig);

?>