<?php

// This is a compiled Agavi configuration file
// Compiled from: /data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/app/config/settings.xml
// Generated by: AgaviSettingConfigHandler
// Date: 2011-11-28T16:38:18+0000

AgaviConfig::fromArray(array (
  'actions.default_module' => 'Default',
  'actions.default_action' => 'Index',
  'actions.error_404_module' => 'Default',
  'actions.error_404_action' => 'Error404',
  'actions.unavailable_module' => 'Default',
  'actions.unavailable_action' => 'Unavailable',
  'actions.module_disabled_module' => 'Default',
  'actions.module_disabled_action' => 'ModuleDisabled',
  'actions.secure_module' => 'Default',
  'actions.secure_action' => 'Secure',
  'actions.login_module' => 'Default',
  'actions.login_action' => 'Login',
  'core.app_name' => 'Classic',
  'core.available' => true,
  'core.debug' => true,
  'core.use_database' => false,
  'core.use_logging' => false,
  'core.use_security' => true,
  'core.use_translation' => false,
  'exception.default_template' => '/data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/libs/agavi/src/exception/templates/shiny.php',
  'exception.templates.console' => '/data/users/mhein/workspaces/ingraph/ingraph/agavi-stub/libs/agavi/src/exception/templates/plaintext.php',
));

?>